// AUTO-GENERATED by scripts/generateAppIcon.mjs — do not edit manually.
// Re-run `node scripts/generateAppIcon.mjs` to regenerate after adding new icons.
import React, { useContext } from 'react';
import Svg, { Circle, Ellipse, Path, Rect } from 'react-native-svg';
import { ThemeContext } from '../lib/ThemeContext';

/**
 * Drop-in replacement for `@expo/vector-icons/Ionicons`.
 * Renders icons as inline SVG via react-native-svg (already a project dependency).
 * Eliminates the ~381 KB Ionicons.ttf font asset from the APK.
 *
 * Usage:  <AppIcon name="home-outline" size={24} color={colors.text} />
 * Default color follows the active theme (`colors.text`) so icons stay visible in dark mode.
 */
export default function AppIcon({ name, size = 24, color, style }) {
  const theme = useContext(ThemeContext);
  const iconColor = color ?? theme?.colors?.text ?? '#000000';
  switch (name) {
    case 'add':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M256 112v288M400 256H112" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'add-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M256 112v288M400 256H112" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'alert-circle-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M448 256c0-106-86-192-192-192S64 150 64 256s86 192 192 192 192-86 192-192Z" fill="none" stroke={iconColor} strokeWidth={32} />
        <Path d="M250.26 166.05 256 288l5.73-121.95a5.74 5.74 0 0 0-5.79-6h0a5.74 5.74 0 0 0-5.68 6" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M256 367.91a20 20 0 1 1 20-20 20 20 0 0 1-20 20" fill={iconColor} />
        </Svg>
      );
    case 'arrow-back':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M244 400 100 256l144-144M120 256h292" fill="none" stroke={iconColor} strokeWidth={48} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'arrow-back-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M244 400 100 256l144-144M120 256h292" fill="none" stroke={iconColor} strokeWidth={48} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'arrow-forward':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M268 112l144 144-144 144M392 256H100" fill="none" stroke={iconColor} strokeWidth={48} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'basket-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M68.4 192A20.38 20.38 0 0 0 48 212.2a17.9 17.9 0 0 0 .8 5.5L100.5 400a40.46 40.46 0 0 0 39.1 29.5h232.8a40.88 40.88 0 0 0 39.3-29.5l51.7-182.3.6-5.5a20.38 20.38 0 0 0-20.4-20.2zm193.32 160.07A42.07 42.07 0 1 1 304 310a42.27 42.27 0 0 1-42.28 42.07Z" fill="none" stroke={iconColor} strokeWidth={32} strokeLinejoin="round" />
        <Path d="m160 192 96-128 96 128" fill="none" stroke={iconColor} strokeWidth={32} strokeLinejoin="round" />
        </Svg>
      );
    case 'business-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M176 416v64M80 32h192a32 32 0 0 1 32 32v412a4 4 0 0 1-4 4H48h0V64a32 32 0 0 1 32-32M320 192h112a32 32 0 0 1 32 32v256h0-160 0V208a16 16 0 0 1 16-16" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M98.08 431.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M98.08 351.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M98.08 271.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M98.08 191.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M98.08 111.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M178.08 351.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M178.08 271.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M178.08 191.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M178.08 111.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M258.08 431.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M258.08 351.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M258.08 271.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79" fill={iconColor} />
        <Ellipse cx={256} cy={176} rx={15.95} ry={16.03} fill={iconColor} />
        <Path d="M258.08 111.87a16 16 0 1 1 13.79-13.79 16 16 0 0 1-13.79 13.79M400 400a16 16 0 1 0 16 16 16 16 0 0 0-16-16M400 320a16 16 0 1 0 16 16 16 16 0 0 0-16-16M400 240a16 16 0 1 0 16 16 16 16 0 0 0-16-16M336 400a16 16 0 1 0 16 16 16 16 0 0 0-16-16M336 320a16 16 0 1 0 16 16 16 16 0 0 0-16-16M336 240a16 16 0 1 0 16 16 16 16 0 0 0-16-16" fill={iconColor} />
        </Svg>
      );
    case 'cafe-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M368 80h64a16 16 0 0 1 16 16v34a46 46 0 0 1-46 46h-34M96 80h272v192a80 80 0 0 1-80 80H176a80 80 0 0 1-80-80zM64 416h336" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'cart':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Circle cx={176} cy={416} r={32} fill={iconColor} />
        <Circle cx={400} cy={416} r={32} fill={iconColor} />
        <Path d="M456.8 120.78a23.92 23.92 0 0 0-18.56-8.78H133.89l-6.13-34.78A16 16 0 0 0 112 64H48a16 16 0 0 0 0 32h50.58l45.66 258.78A16 16 0 0 0 160 368h256a16 16 0 0 0 0-32H173.42l-5.64-32h241.66A24.07 24.07 0 0 0 433 284.71l28.8-144a24 24 0 0 0-5-19.93" fill={iconColor} />
        </Svg>
      );
    case 'cart-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Circle cx={176} cy={416} r={16} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Circle cx={400} cy={416} r={16} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M48 80h64l48 272h256" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M160 288h249.44a8 8 0 0 0 7.85-6.43l28.8-144a8 8 0 0 0-7.85-9.57H128" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'cash-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Rect rx={16} ry={16} width={448} height={256} x={32} y={80} fill="none" stroke={iconColor} strokeWidth={32} strokeLinejoin="round" />
        <Path d="M64 384h384M96 432h320" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Circle cx={256} cy={208} r={80} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M480 160a80 80 0 0 1-80-80M32 160a80 80 0 0 0 80-80M480 256a80 80 0 0 0-80 80M32 256a80 80 0 0 1 80 80" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'chatbubble-ellipses-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M87.48 380c1.2-4.38-1.43-10.47-3.94-14.86a43 43 0 0 0-2.54-3.8 199.8 199.8 0 0 1-33-110C47.64 139.09 140.72 48 255.82 48 356.2 48 440 117.54 459.57 209.85a199 199 0 0 1 4.43 41.64c0 112.41-89.49 204.93-204.59 204.93-18.31 0-43-4.6-56.47-8.37s-26.92-8.77-30.39-10.11a31.1 31.1 0 0 0-11.13-2.07 30.7 30.7 0 0 0-12.08 2.43L81.5 462.78a16 16 0 0 1-4.66 1.22 9.61 9.61 0 0 1-9.58-9.74 16 16 0 0 1 .6-3.29Z" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" />
        <Circle cx={160} cy={256} r={32} fill={iconColor} />
        <Circle cx={256} cy={256} r={32} fill={iconColor} />
        <Circle cx={352} cy={256} r={32} fill={iconColor} />
        </Svg>
      );
    case 'chatbubbles-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M431 320.6c-1-3.6 1.2-8.6 3.3-12.2a34 34 0 0 1 2.1-3.1A162 162 0 0 0 464 215c.3-92.2-77.5-167-173.7-167-83.9 0-153.9 57.1-170.3 132.9a160.7 160.7 0 0 0-3.7 34.2c0 92.3 74.8 169.1 171 169.1 15.3 0 35.9-4.6 47.2-7.7s22.5-7.2 25.4-8.3a26.4 26.4 0 0 1 9.3-1.7 26 26 0 0 1 10.1 2l56.7 20.1a13.5 13.5 0 0 0 3.9 1 8 8 0 0 0 8-8 13 13 0 0 0-.5-2.7Z" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" />
        <Path d="M66.46 232a146.23 146.23 0 0 0 6.39 152.67c2.31 3.49 3.61 6.19 3.21 8s-11.93 61.87-11.93 61.87a8 8 0 0 0 2.71 7.68A8.17 8.17 0 0 0 72 464a7.3 7.3 0 0 0 2.91-.6l56.21-22a15.7 15.7 0 0 1 12 .2c18.94 7.38 39.88 12 60.83 12A159.2 159.2 0 0 0 284 432.11" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" />
        </Svg>
      );
    case 'checkmark':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M416 128 192 384l-96-96" fill="none" stroke={iconColor} strokeWidth={48} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'checkmark-circle':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M256 48C141.31 48 48 141.31 48 256s93.31 208 208 208 208-93.31 208-208S370.69 48 256 48m108.25 138.29-134.4 160a16 16 0 0 1-12 5.71h-.27a16 16 0 0 1-11.89-5.3l-57.6-64a16 16 0 1 1 23.78-21.4l45.29 50.32 122.59-145.91a16 16 0 0 1 24.5 20.58" fill={iconColor} />
        </Svg>
      );
    case 'checkmark-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M416 128 192 384l-96-96" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'chevron-down':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="m112 184 144 144 144-144" fill="none" stroke={iconColor} strokeWidth={48} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'chevron-up':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="m112 328 144-144 144 144" fill="none" stroke={iconColor} strokeWidth={48} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'chevron-forward':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="m184 112 144 144-144 144" fill="none" stroke={iconColor} strokeWidth={48} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'close':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="m289.94 256 95-95A24 24 0 0 0 351 127l-95 95-95-95a24 24 0 0 0-34 34l95 95-95 95a24 24 0 1 0 34 34l95-95 95 95a24 24 0 0 0 34-34Z" fill={iconColor} />
        </Svg>
      );
    case 'close-circle':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M256 48C141.31 48 48 141.31 48 256s93.31 208 208 208 208-93.31 208-208S370.69 48 256 48m75.31 260.69a16 16 0 1 1-22.62 22.62L256 278.63l-52.69 52.68a16 16 0 0 1-22.62-22.62L233.37 256l-52.68-52.69a16 16 0 0 1 22.62-22.62L256 233.37l52.69-52.68a16 16 0 0 1 22.62 22.62L278.63 256Z" fill={iconColor} />
        </Svg>
      );
    case 'close-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M368 368 144 144M368 144 144 368" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'document-text-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M416 221.25V416a48 48 0 0 1-48 48H144a48 48 0 0 1-48-48V96a48 48 0 0 1 48-48h98.75a32 32 0 0 1 22.62 9.37l141.26 141.26a32 32 0 0 1 9.37 22.62Z" fill="none" stroke={iconColor} strokeWidth={32} strokeLinejoin="round" />
        <Path d="M256 56v120a32 32 0 0 0 32 32h120M176 288h160M176 368h160" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'eye':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Circle cx={256} cy={256} r={64} fill={iconColor} />
        <Path d="M490.84 238.6c-26.46-40.92-60.79-75.68-99.27-100.53C349 110.55 302 96 255.66 96c-42.52 0-84.33 12.15-124.27 36.11-40.73 24.43-77.63 60.12-109.68 106.07a31.92 31.92 0 0 0-.64 35.54c26.41 41.33 60.4 76.14 98.28 100.65C162 402 207.9 416 255.66 416c46.71 0 93.81-14.43 136.2-41.72 38.46-24.77 72.72-59.66 99.08-100.92a32.2 32.2 0 0 0-.1-34.76M256 352a96 96 0 1 1 96-96 96.11 96.11 0 0 1-96 96" fill={iconColor} />
        </Svg>
      );
    case 'eye-off':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M432 448a15.92 15.92 0 0 1-11.31-4.69l-352-352a16 16 0 0 1 22.62-22.62l352 352A16 16 0 0 1 432 448M248 315.85l-51.79-51.79a2 2 0 0 0-3.39 1.69 64.11 64.11 0 0 0 53.49 53.49 2 2 0 0 0 1.69-3.39M264 196.15 315.87 248a2 2 0 0 0 3.4-1.69 64.13 64.13 0 0 0-53.55-53.55 2 2 0 0 0-1.72 3.39" fill={iconColor} />
        <Path d="M491 273.36a32.2 32.2 0 0 0-.1-34.76c-26.46-40.92-60.79-75.68-99.27-100.53C349 110.55 302 96 255.68 96a226.5 226.5 0 0 0-71.82 11.79 4 4 0 0 0-1.56 6.63l47.24 47.24a4 4 0 0 0 3.82 1.05 96 96 0 0 1 116 116 4 4 0 0 0 1.05 3.81l67.95 68a4 4 0 0 0 5.4.24 343.8 343.8 0 0 0 67.24-77.4M256 352a96 96 0 0 1-93.3-118.63 4 4 0 0 0-1.05-3.81l-66.84-66.87a4 4 0 0 0-5.41-.23c-24.39 20.81-47 46.13-67.67 75.72a31.92 31.92 0 0 0-.64 35.54c26.41 41.33 60.39 76.14 98.28 100.65C162.06 402 207.92 416 255.68 416a238.2 238.2 0 0 0 72.64-11.55 4 4 0 0 0 1.61-6.64l-47.47-47.46a4 4 0 0 0-3.81-1.05A96 96 0 0 1 256 352" fill={iconColor} />
        </Svg>
      );
    case 'eye-off-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M432 448a15.92 15.92 0 0 1-11.31-4.69l-352-352a16 16 0 0 1 22.62-22.62l352 352A16 16 0 0 1 432 448M255.66 384c-41.49 0-81.5-12.28-118.92-36.5-34.07-22-64.74-53.51-88.7-91v-.08c19.94-28.57 41.78-52.73 65.24-72.21a2 2 0 0 0 .14-2.94L93.5 161.38a2 2 0 0 0-2.71-.12c-24.92 21-48.05 46.76-69.08 76.92a31.92 31.92 0 0 0-.64 35.54c26.41 41.33 60.4 76.14 98.28 100.65C162 402 207.9 416 255.66 416a239.1 239.1 0 0 0 75.8-12.58 2 2 0 0 0 .77-3.31l-21.58-21.58a4 4 0 0 0-3.83-1 204.8 204.8 0 0 1-51.16 6.47M490.84 238.6c-26.46-40.92-60.79-75.68-99.27-100.53C349 110.55 302 96 255.66 96a227.3 227.3 0 0 0-74.89 12.83 2 2 0 0 0-.75 3.31l21.55 21.55a4 4 0 0 0 3.88 1 192.8 192.8 0 0 1 50.21-6.69c40.69 0 80.58 12.43 118.55 37 34.71 22.4 65.74 53.88 89.76 91a.13.13 0 0 1 0 .16 310.7 310.7 0 0 1-64.12 72.73 2 2 0 0 0-.15 2.95l19.9 19.89a2 2 0 0 0 2.7.13 343.5 343.5 0 0 0 68.64-78.48 32.2 32.2 0 0 0-.1-34.78" fill={iconColor} />
        <Path d="M256 160a96 96 0 0 0-21.37 2.4 2 2 0 0 0-1 3.38l112.59 112.56a2 2 0 0 0 3.38-1A96 96 0 0 0 256 160M165.78 233.66a2 2 0 0 0-3.38 1 96 96 0 0 0 115 115 2 2 0 0 0 1-3.38Z" fill={iconColor} />
        </Svg>
      );
    case 'eye-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M255.66 112c-77.94 0-157.89 45.11-220.83 135.33a16 16 0 0 0-.27 17.77C82.92 340.8 161.8 400 255.66 400c92.84 0 173.34-59.38 221.79-135.25a16.14 16.14 0 0 0 0-17.47C428.89 172.28 347.8 112 255.66 112" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Circle cx={256} cy={256} r={80} fill="none" stroke={iconColor} strokeWidth={32} />
        </Svg>
      );
    case 'home':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M261.56 101.28a8 8 0 0 0-11.06 0L66.4 277.15a8 8 0 0 0-2.47 5.79L63.9 448a32 32 0 0 0 32 32H192a16 16 0 0 0 16-16V328a8 8 0 0 1 8-8h80a8 8 0 0 1 8 8v136a16 16 0 0 0 16 16h96.06a32 32 0 0 0 32-32V282.94a8 8 0 0 0-2.47-5.79Z" fill={iconColor} />
        <Path d="m490.91 244.15-74.8-71.56V64a16 16 0 0 0-16-16h-48a16 16 0 0 0-16 16v32l-57.92-55.38C272.77 35.14 264.71 32 256 32c-8.68 0-16.72 3.14-22.14 8.63l-212.7 203.5c-6.22 6-7 15.87-1.34 22.37A16 16 0 0 0 43 267.56L250.5 69.28a8 8 0 0 1 11.06 0l207.52 198.28a16 16 0 0 0 22.59-.44c6.14-6.36 5.63-16.86-.76-22.97" fill={iconColor} />
        </Svg>
      );
    case 'home-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M80 212v236a16 16 0 0 0 16 16h96V328a24 24 0 0 1 24-24h80a24 24 0 0 1 24 24v136h96a16 16 0 0 0 16-16V212" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M480 256 266.89 52c-5-5.28-16.69-5.34-21.78 0L32 256M400 179V64h-48v69" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'information-circle-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M248 64C146.39 64 64 146.39 64 248s82.39 184 184 184 184-82.39 184-184S349.61 64 248 64Z" fill="none" stroke={iconColor} strokeWidth={32} />
        <Path d="M220 220h32v116" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M208 340h88" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" />
        <Path d="M248 130a26 26 0 1 0 26 26 26 26 0 0 0-26-26" fill={iconColor} />
        </Svg>
      );
    case 'key-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M218.1 167.17c0 13 0 25.6 4.1 37.4-43.1 50.6-156.9 184.3-167.5 194.5a20.17 20.17 0 0 0-6.7 15c0 8.5 5.2 16.7 9.6 21.3 6.6 6.9 34.8 33 40 28 15.4-15 18.5-19 24.8-25.2 9.5-9.3-1-28.3 2.3-36s6.8-9.2 12.5-10.4 15.8 2.9 23.7 3c8.3.1 12.8-3.4 19-9.2 5-4.6 8.6-8.9 8.7-15.6.2-9-12.8-20.9-3.1-30.4s23.7 6.2 34 5 22.8-15.5 24.1-21.6-11.7-21.8-9.7-30.7c.7-3 6.8-10 11.4-11s25 6.9 29.6 5.9c5.6-1.2 12.1-7.1 17.4-10.4 15.5 6.7 29.6 9.4 47.7 9.4 68.5 0 124-53.4 124-119.2S408.5 48 340 48s-121.9 53.37-121.9 119.17ZM400 144a32 32 0 1 1-32-32 32 32 0 0 1 32 32Z" fill="none" stroke={iconColor} strokeWidth={32} strokeLinejoin="round" />
        </Svg>
      );
    case 'leaf-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M321.89 171.42C233 114 141 155.22 56 65.22c-19.8-21-8.3 235.5 98.1 332.7 77.79 71 197.9 63.08 238.4-5.92s18.28-163.17-70.61-220.58" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M173 253c86 81 175 129 292 147" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'location':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Circle cx={256} cy={192} r={32} fill={iconColor} />
        <Path d="M256 32c-88.22 0-160 68.65-160 153 0 40.17 18.31 93.59 54.42 158.78 29 52.34 62.55 99.67 80 123.22a31.75 31.75 0 0 0 51.22 0c17.42-23.55 51-70.88 80-123.22C397.69 278.61 416 225.19 416 185c0-84.35-71.78-153-160-153m0 224a64 64 0 1 1 64-64 64.07 64.07 0 0 1-64 64" fill={iconColor} />
        </Svg>
      );
    case 'location-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M256 48c-79.5 0-144 61.39-144 137 0 87 96 224.87 131.25 272.49a15.77 15.77 0 0 0 25.5 0C304 409.89 400 272.07 400 185c0-75.61-64.5-137-144-137" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Circle cx={256} cy={192} r={48} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'lock-closed-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M336 208v-95a80 80 0 0 0-160 0v95" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Rect rx={48} ry={48} width={320} height={272} x={96} y={208} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'lock-open-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M336 112a80 80 0 0 0-160 0v96" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Rect rx={48} ry={48} width={320} height={272} x={96} y={208} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'log-out-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M304 336v40a40 40 0 0 1-40 40H104a40 40 0 0 1-40-40V136a40 40 0 0 1 40-40h152c22.09 0 48 17.91 48 40v40M368 336l80-80-80-80M176 256h256" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'logo-facebook':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M480 257.35c0-123.7-100.3-224-224-224s-224 100.3-224 224c0 111.8 81.9 204.47 189 221.29V322.12h-56.89v-64.77H221V208c0-56.13 33.45-87.16 84.61-87.16 24.51 0 50.15 4.38 50.15 4.38v55.13H327.5c-27.81 0-36.51 17.26-36.51 35v42h62.12l-9.92 64.77H291v156.54c107.1-16.81 189-109.48 189-221.31" fill={iconColor} />
        </Svg>
      );
    case 'logo-instagram':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M349.33 69.33a93.62 93.62 0 0 1 93.34 93.34v186.66a93.62 93.62 0 0 1-93.34 93.34H162.67a93.62 93.62 0 0 1-93.34-93.34V162.67a93.62 93.62 0 0 1 93.34-93.34zm0-37.33H162.67C90.8 32 32 90.8 32 162.67v186.66C32 421.2 90.8 480 162.67 480h186.66C421.2 480 480 421.2 480 349.33V162.67C480 90.8 421.2 32 349.33 32" fill={iconColor} />
        <Path d="M377.33 162.67a28 28 0 1 1 28-28 27.94 27.94 0 0 1-28 28M256 181.33A74.67 74.67 0 1 1 181.33 256 74.75 74.75 0 0 1 256 181.33m0-37.33a112 112 0 1 0 112 112 112 112 0 0 0-112-112" fill={iconColor} />
        </Svg>
      );
    case 'logo-twitter':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M496 109.5a201.8 201.8 0 0 1-56.55 15.3 97.5 97.5 0 0 0 43.33-53.6 197.7 197.7 0 0 1-62.56 23.5A99.14 99.14 0 0 0 348.31 64c-54.42 0-98.46 43.4-98.46 96.9a93.2 93.2 0 0 0 2.54 22.1 280.7 280.7 0 0 1-203-101.3A95.7 95.7 0 0 0 36 130.4c0 33.6 17.53 63.3 44 80.7A97.5 97.5 0 0 1 35.22 199v1.2c0 47 34 86.1 79 95a100.8 100.8 0 0 1-25.94 3.4 94.4 94.4 0 0 1-18.51-1.8c12.51 38.5 48.92 66.5 92.05 67.3A199.6 199.6 0 0 1 39.5 405.6a203 203 0 0 1-23.5-1.4A278.7 278.7 0 0 0 166.74 448c181.36 0 280.44-147.7 280.44-275.8 0-4.2-.11-8.4-.31-12.5A198.5 198.5 0 0 0 496 109.5" fill={iconColor} />
        </Svg>
      );
    case 'mail-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Rect rx={40} ry={40} width={416} height={320} x={48} y={96} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="m112 160 144 112 144-112" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'moon-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M160 136c0-30.62 4.51-61.61 16-88C99.57 81.27 48 159.32 48 248c0 119.29 96.71 216 216 216 88.68 0 166.73-51.57 200-128-26.39 11.49-57.38 16-88 16-119.29 0-216-96.71-216-216" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'notifications-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M427.68 351.43C402 320 383.87 304 383.87 217.35 383.87 138 343.35 109.73 310 96c-4.43-1.82-8.6-6-9.95-10.55C294.2 65.54 277.8 48 256 48s-38.21 17.55-44 37.47c-1.35 4.6-5.52 8.71-9.95 10.53-33.39 13.75-73.87 41.92-73.87 121.35C128.13 304 110 320 84.32 351.43 73.68 364.45 83 384 101.61 384h308.88c18.51 0 27.77-19.61 17.19-32.57M320 384v16a64 64 0 0 1-128 0v-16" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'person':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M332.64 64.58C313.18 43.57 286 32 256 32c-30.16 0-57.43 11.5-76.8 32.38-19.58 21.11-29.12 49.8-26.88 80.78C156.76 206.28 203.27 256 256 256s99.16-49.71 103.67-110.82c2.27-30.7-7.33-59.33-27.03-80.6M432 480H80a31 31 0 0 1-24.2-11.13c-6.5-7.77-9.12-18.38-7.18-29.11C57.06 392.94 83.4 353.61 124.8 326c36.78-24.51 83.37-38 131.2-38s94.42 13.5 131.2 38c41.4 27.6 67.74 66.93 76.18 113.75 1.94 10.73-.68 21.34-7.18 29.11A31 31 0 0 1 432 480" fill={iconColor} />
        </Svg>
      );
    case 'person-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M344 144c-3.92 52.87-44 96-88 96s-84.15-43.12-88-96c-4-55 35-96 88-96s92 42 88 96" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M256 304c-87 0-175.3 48-191.64 138.6C62.39 453.52 68.57 464 80 464h352c11.44 0 17.62-10.48 15.65-21.4C431.3 352 343 304 256 304Z" fill="none" stroke={iconColor} strokeWidth={32} />
        </Svg>
      );
    case 'receipt':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M483.82 32.45a16.28 16.28 0 0 0-11.23 1.37L448 46.1l-24.8-12.4a16 16 0 0 0-14.31 0l-25.11 12.41L359 33.7a16 16 0 0 0-14.36 0L320 46.07l-24.45-12.34a16 16 0 0 0-14.35-.06L256 46.12l-24.8-12.43a16.05 16.05 0 0 0-14.33 0L192 46.1l-24.84-12.41a16 16 0 0 0-19.36 3.94 16.25 16.25 0 0 0-3.8 10.65V288l.05.05H336a32 32 0 0 1 32 32V424c0 30.93 33.07 56 64 56h12a52 52 0 0 0 52-52V48a16 16 0 0 0-12.18-15.55M416 240H288.5c-8.64 0-16.1-6.64-16.48-15.28A16 16 0 0 1 288 208h127.5c8.64 0 16.1 6.64 16.48 15.28A16 16 0 0 1 416 240m0-80H224.5c-8.64 0-16.1-6.64-16.48-15.28A16 16 0 0 1 224 128h191.5c8.64 0 16.1 6.64 16.48 15.28A16 16 0 0 1 416 160" fill={iconColor} />
        <Path d="M336 424v-88a16 16 0 0 0-16-16H48a32.1 32.1 0 0 0-32 32.05c0 50.55 5.78 71.57 14.46 87.57C45.19 466.79 71.86 480 112 480h245.68a4 4 0 0 0 2.85-6.81C351.07 463.7 336 451 336 424" fill={iconColor} />
        </Svg>
      );
    case 'receipt-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M160 336V48l32 16 32-16 31.94 16 32.37-16L320 64l31.79-16 31.93 16L416 48l32.01 16L480 48v224" fill="none" stroke={iconColor} strokeWidth={32} strokeLinejoin="round" />
        <Path d="M480 272v112a80 80 0 0 1-80 80 80 80 0 0 1-80-80v-48H48a15.86 15.86 0 0 0-16 16c0 64 6.74 112 80 112h288" fill="none" stroke={iconColor} strokeWidth={32} strokeLinejoin="round" />
        <Path d="M224 144h192M288 224h128" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'refresh':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M320 146s24.36-12-64-12a160 160 0 1 0 160 160" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" />
        <Path d="m256 58 80 80-80 80" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'refresh-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M320 146s24.36-12-64-12a160 160 0 1 0 160 160" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" />
        <Path d="m256 58 80 80-80 80" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'remove':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M400 256H112" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'remove-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M400 256H112" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'restaurant':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M357.57 223.94a79.48 79.48 0 0 0 56.58-23.44l77-76.95c6.09-6.09 6.65-16 .85-22.39a16 16 0 0 0-23.17-.56l-68.63 68.58a12.29 12.29 0 0 1-17.37 0c-4.79-4.78-4.53-12.86.25-17.64l68.33-68.33a16 16 0 0 0-.56-23.16A15.62 15.62 0 0 0 440.27 56a16.7 16.7 0 0 0-11.81 4.9l-68.27 68.26a12.29 12.29 0 0 1-17.37 0c-4.78-4.78-4.53-12.86.25-17.64l68.33-68.31a16 16 0 0 0-.56-23.16A15.62 15.62 0 0 0 400.26 16a16.73 16.73 0 0 0-11.81 4.9L311.5 97.85a79.5 79.5 0 0 0-23.44 56.59v8.23a16 16 0 0 1-4.69 11.33l-35.61 35.62a4 4 0 0 1-5.66 0L68.82 36.33a16 16 0 0 0-22.58-.06C31.09 51.28 23 72.47 23 97.54c-.1 41.4 21.66 89 56.79 124.08l85.45 85.45A64.8 64.8 0 0 0 211 326a64 64 0 0 0 16.21-2.08 16.2 16.2 0 0 1 4.07-.53 15.93 15.93 0 0 1 10.83 4.25l11.39 10.52a16.12 16.12 0 0 1 4.6 11.23v5.54a47.73 47.73 0 0 0 13.77 33.65l90.05 91.57.09.1a53.29 53.29 0 0 0 75.36-75.37L302.39 269.9a4 4 0 0 1 0-5.66L338 228.63a16 16 0 0 1 11.32-4.69Z" fill={iconColor} />
        <Path d="M211 358a97.32 97.32 0 0 1-68.36-28.25l-13.86-13.86a8 8 0 0 0-11.3 0l-85 84.56c-15.15 15.15-20.56 37.45-13.06 59.29a31 31 0 0 0 1.49 3.6C31 484 50.58 496 72 496a55.68 55.68 0 0 0 39.64-16.44L225 365.66a4.69 4.69 0 0 0 1.32-3.72v-.26a4.63 4.63 0 0 0-5.15-4.27A97 97 0 0 1 211 358" fill={iconColor} />
        </Svg>
      );
    case 'search':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M456.69 421.39 362.6 327.3a173.8 173.8 0 0 0 34.84-104.58C397.44 126.38 319.06 48 222.72 48S48 126.38 48 222.72s78.38 174.72 174.72 174.72A173.8 173.8 0 0 0 327.3 362.6l94.09 94.09a25 25 0 0 0 35.3-35.3M97.92 222.72a124.8 124.8 0 1 1 124.8 124.8 124.95 124.95 0 0 1-124.8-124.8" fill={iconColor} />
        </Svg>
      );
    case 'send-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M470.3 271.15 43.16 447.31a7.83 7.83 0 0 1-11.16-7V327a8 8 0 0 1 6.51-7.86l247.62-47c17.36-3.29 17.36-28.15 0-31.44l-247.63-47a8 8 0 0 1-6.5-7.85V72.59c0-5.74 5.88-10.26 11.16-8L470.3 241.76a16 16 0 0 1 0 29.39" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'share-social-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Circle cx={128} cy={256} r={48} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Circle cx={384} cy={112} r={48} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Circle cx={384} cy={400} r={48} fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="m169.83 279.53 172.34 96.94M342.17 135.53l-172.34 96.94" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'shield-checkmark-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M336 176 225.2 304 176 255.8" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M463.1 112.37C373.68 96.33 336.71 84.45 256 48c-80.71 36.45-117.68 48.33-207.1 64.37C32.7 369.13 240.58 457.79 256 464c15.42-6.21 223.3-94.87 207.1-351.63" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'sparkles-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M259.92 262.91 216.4 149.77a9 9 0 0 0-16.8 0l-43.52 113.14a9 9 0 0 1-5.17 5.17L37.77 311.6a9 9 0 0 0 0 16.8l113.14 43.52a9 9 0 0 1 5.17 5.17l43.52 113.14a9 9 0 0 0 16.8 0l43.52-113.14a9 9 0 0 1 5.17-5.17l113.14-43.52a9 9 0 0 0 0-16.8l-113.14-43.52a9 9 0 0 1-5.17-5.17M108 68 88 16 68 68 16 88l52 20 20 52 20-52 52-20zM426.67 117.33 400 48l-26.67 69.33L304 144l69.33 26.67L400 240l26.67-69.33L496 144z" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'storefront':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M480 448h-12a4 4 0 0 1-4-4V273.51a4 4 0 0 0-5.24-3.86 105 105 0 0 1-28.32 4.78c-1.18 0-2.3.05-3.4.05a108.2 108.2 0 0 1-52.85-13.64 8.23 8.23 0 0 0-8 0 108.2 108.2 0 0 1-52.84 13.64 106.1 106.1 0 0 1-52.46-13.79 8.21 8.21 0 0 0-8.09 0 108.14 108.14 0 0 1-53.16 13.8 106.2 106.2 0 0 1-52.77-14 8.25 8.25 0 0 0-8.16 0 106.2 106.2 0 0 1-52.77 14c-1.09 0-2.19 0-3.37-.05h-.06a105 105 0 0 1-29.28-5.09 4 4 0 0 0-5.23 3.8V444a4 4 0 0 1-4 4H32.5c-8.64 0-16.1 6.64-16.48 15.28A16 16 0 0 0 32 480h447.5c8.64 0 16.1-6.64 16.48-15.28A16 16 0 0 0 480 448m-256-68a4 4 0 0 1-4 4h-88a4 4 0 0 1-4-4v-64a12 12 0 0 1 12-12h72a12 12 0 0 1 12 12Zm156 68h-72a4 4 0 0 1-4-4V316a12 12 0 0 1 12-12h56a12 12 0 0 1 12 12v128a4 4 0 0 1-4 4M492.57 170.28l-42.92-98.49C438.41 47.62 412.74 32 384.25 32H127.7c-28.49 0-54.16 15.62-65.4 39.79l-42.92 98.49c-9 19.41 2.89 39.34 2.9 39.35l.28.45c.49.78 1.36 2 1.89 2.78.05.06.09.13.14.2l5 6.05a8 8 0 0 0 .6.65l5 4.83.42.36a69.7 69.7 0 0 0 9.39 6.78v.05a74 74 0 0 0 36 10.67h2.47a76.08 76.08 0 0 0 51.89-20.31l.33-.31a7.94 7.94 0 0 1 10.89 0l.33.31a77.3 77.3 0 0 0 104.46 0 8 8 0 0 1 10.87 0 77.31 77.31 0 0 0 104.21.23 7.88 7.88 0 0 1 10.71 0 76.8 76.8 0 0 0 52.31 20.08h2.49a71.35 71.35 0 0 0 35-10.7c.95-.57 1.86-1.17 2.78-1.77A71.3 71.3 0 0 0 488 212.17l1.74-2.63q.26-.4.48-.84c1.66-3.38 10.56-20.76 2.35-38.42" fill={iconColor} />
        </Svg>
      );
    case 'storefront-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M448 448V240M64 240v208M382.47 48H129.53c-21.79 0-41.47 12-49.93 30.46L36.3 173c-14.58 31.81 9.63 67.85 47.19 69h2c31.4 0 56.85-25.18 56.85-52.23 0 27 25.46 52.23 56.86 52.23s56.8-23.38 56.8-52.23c0 27 25.45 52.23 56.85 52.23s56.86-23.38 56.86-52.23c0 28.85 25.45 52.23 56.85 52.23h1.95c37.56-1.17 61.77-37.21 47.19-69l-43.3-94.54C423.94 60 404.26 48 382.47 48M32 464h448M136 288h80a24 24 0 0 1 24 24v88h0-128 0v-88a24 24 0 0 1 24-24M288 464V312a24 24 0 0 1 24-24h64a24 24 0 0 1 24 24v152" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'time-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M256 64C150 64 64 150 64 256s86 192 192 192 192-86 192-192S362 64 256 64Z" fill="none" stroke={iconColor} strokeWidth={32} />
        <Path d="M256 128v144h96" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'trash-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="m112 112 20 320c.95 18.49 14.4 32 32 32h184c17.67 0 30.87-13.51 32-32l20-320" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="M80 112h352" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" />
        <Path d="M192 112V72h0a23.93 23.93 0 0 1 24-24h80a23.93 23.93 0 0 1 24 24h0v40M256 176v224M184 176l8 224M328 176l-8 224" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    case 'wallet-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Rect rx={48} ry={48} width={416} height={288} x={48} y={144} fill="none" stroke={iconColor} strokeWidth={32} strokeLinejoin="round" />
        <Path d="M411.36 144v-30A50 50 0 0 0 352 64.9L88.64 109.85A50 50 0 0 0 48 159v49" fill="none" stroke={iconColor} strokeWidth={32} strokeLinejoin="round" />
        <Path d="M368 320a32 32 0 1 1 32-32 32 32 0 0 1-32 32" fill={iconColor} />
        </Svg>
      );
    case 'wifi-outline':
      return (
        <Svg viewBox="0 0 512 512" width={size} height={size} style={style}>
        <Path d="M318.586 363.5 256 424l-62.586-60.5S212 336 256 336s62.586 27.5 62.586 27.5M407.31 278 372 312s-41-46-116-46-116 46-116 46l-35.31-34S142.5 214 256 214s151.31 64 151.31 64" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        <Path d="m496 192-36.69 35.5S386.5 141 256 141 52.69 227.5 52.69 227.5L16 192S88 88 256 88s240 104 240 104" fill="none" stroke={iconColor} strokeWidth={32} strokeLinecap="round" strokeLinejoin="round" />
        </Svg>
      );
    default:
      // Unknown icon name — render empty placeholder so layout is preserved
      return <Svg viewBox="0 0 512 512" width={size} height={size} style={style} />;
  }
}
